---
- name: Set release directory fact
  set_fact: release_destination="{{ release_location }}/{{ release_version }}"

- name: Pull source files into the release directory
  git: repo=/vagrant dest={{ release_destination }} version={{ release_version }}
  notify:
      - chown /var/www

- name: Generate parameters file
  template: src=parameters.yml.j2 dest="{{ release_destination }}/app/config/parameters.yml"

- name: Composer install
  shell: "cd {{ release_destination }} && composer install --prefer-dist --no-interaction --optimize-autoloader"

- name: Migrate the database
  command: "php {{ release_destination }}/bin/console doctrine:migrations:migrate --env=prod --no-interaction"
  notify:
      - chown /var/www

- name: Symlink to current directory
  file: state=link src={{ release_destination }} path={{ deployment_location }}/current