---
- name: Install Nginx
  sudo: yes
  apt: pkg=nginx state=latest

- name: Set permissions on nginx
  lineinfile: "dest=/etc/nginx/nginx.conf state=present regexp='^;?user' line='user vagrant;'"
  notify: restart nginx

- name: Add Nginx vhosts
  sudo: yes
  template: src=default-{{ item.value.environment }}.j2 dest=/etc/nginx/sites-available/{{ item.key }}
  notify: restart nginx
  with_dict: "{{ nginx.vhosts }}"

- name: Enable Nginx vhosts
  sudo: yes
  file: src=/etc/nginx/sites-available/{{ item.key }} dest=/etc/nginx/sites-enabled/{{ item.key }} owner=root group=root state=link
  notify: restart nginx
  with_dict: "{{ nginx.vhosts }}"
