---
- hosts: all
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - server
    - vagrant_local
    - nginx
    - mysql
    - sqlite
    - php
    - xdebug
    - composer
    - app
    - geerlingguy.jenkins
